version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gomark
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"

  backend:
    build: .
    restart: always
    depends_on:
      - db
      - redis
      - rabbitmq
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/gomark?sslmode=disable"
      REDIS_HOST: "redis:6379"
    ports:
      - "8080:8080"

volumes:
  pgdata:
