# Use Golang base image
FROM golang:1.22.11 AS builder
WORKDIR /app

# Copy go.mod and go.sum, then download dependencies
COPY go.mod go.sum ./
RUN go mod tidy

# Copy application source code
COPY . .

# Build the application
RUN go build -o gomark-backend

# Use a lightweight container for runtime
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/gomark-backend .

# Expose the API port
EXPOSE 8080

# Run the application
CMD ["./gomark-backend"]

